name: PR check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3.1.0
      - run: ./gradlew allTests
