name: PR check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3.1.0
      - run: ./gradlew allTests
